= Jekyll frontend build plugin

This is a very minimal plugin that post-processes front-end assets,
enabling you to use the latest ES features
with fewer worries about cross-browser compatibility.

This plugin depends on Node/NPM and currently uses Babel.

Caveats:

* You may need to include Babel’s polyfill script explicitly.

Roadmap:

* Post-process the CSS with at least auto-prefixer (https://github.com/riboseinc/jekyll-plugin-frontend-build/issues/2[#2])
* Combine front-end assets into a few packages (bulk of JS, bulk of CSS) and minify it (https://github.com/riboseinc/jekyll-plugin-frontend-build/issues/3[#3])
* (?) Use Web components, e.g. Polymer

== Usage instructions

=== Requirements

This plugin requires Node & NPM to be available in Jekyll build environment.

=== Installation

It's probably the easiest to add following to the `Gemfile`, so that Jekyll will
pick this plugin up automatically:

----
group :jekyll_plugins do
  gem "jekyll-plugin-frontend-build"
end
----

For other options, read https://jekyllrb.com/docs/plugins/installation/[
Jekyll documentation].

=== Configuration options

You can customize plugin's behaviour in site's `_config.yml`,
in `frontend_builder` section.  Following options are supported:

`babel_config_path`::
  Path to Babel configuration file (see section below), relative to site's
  source directory (typically project root).  When unset, a pre-defined
  configuration is used.  By default it is unset.

`javascripts_path`::
  Path to directory which contains JavaScript files to be processed, relative to
  site's source directory (typically project root).  Defaults to `./assets/js`.

Example:

._config.yml
[source,yaml]
----
frontend_builder:
  babel_config_path: babel.config.js
  javascripts_path: assets/javascript
----

=== Providing custom Babel configuration

Usually you'll want to do that.

Just save following listing as `.babel.config.js`, update it according to your
needs, and set `frontend_builder` -> `babel_config_path` in `_config.yml` to
path to that file.

.babel.config.js
[source,javascript]
----
const presets = [
  [
    "@babel/env",
    {
      targets: {
        ie: "10",
        edge: "17",
        firefox: "60",
        chrome: "67",
        safari: "11.1",
      },
    },
  ],
];

module.exports = { presets };
----

If you want to learn more about Babel configuration files, read on:

- https://babeljs.io/docs/en/usage
- https://babeljs.io/docs/en/babel-preset-env

=== Including Babel polyfill

For certain functionality, Babel requires a polyfill script to be executed
before your code.

The plugin copies the pollyfill under `_site/assets/js`,
so including it isn’t difficult.

To include Babel polyfill in normal browser window context:

[source,html]
----
<script src="/assets/js/babel-polyfill.js"></script>
----

To include Babel polyfill in Web worker context:

[source,javascript]
----
importScripts('/assets/js/babel-polyfill.js');

// The rest of the code
----

== Troubleshooting

=== Verbose output

When `jekyll build` is run with `--verbose` option, this plugin prints more
details, which may help in diagnosing what went wrong.

=== `ReferenceError: regeneratorRuntime is not defined`

This might happen in worker context.

Solution: include Babel polyfill before your code
(see the Including Babel polyfill section).

=== `Symbol` or `Symbol.iterator` is not defined

This might happen in browser window context.

Solution: include Babel polyfill before your code
(see the Including Babel polyfill section).

== Credits

This gem is developed, maintained and funded by {ribose}[Ribose Inc.]

== License

The gem is available as open source under the terms of the
https://opensource.org/licenses/MIT[MIT License].
